# Culture lives by celebrating and sharing it,
# not by hating other cultures
---
  env:
    node: false
    browser: true
  plugins:
    - html
  globals:
    riot: true
    XMLHttpRequest: true
    app: true
  rules:
    eqeqeq: [error, smart]
    indent: [error, 2]
    no-bitwise: [error, { allow: ["|"] }]
    linebreak-style: [error, unix]
    no-cond-assign: off
    no-console: [warn, { allow: [warn, error] }]
    no-unexpected-multiline: error
    quotes: [error, single, avoid-escape]
    semi: [error, never]
